# Generated by Django 4.1.3 on 2022-12-03 23:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='finishmodel',
            name='file_path',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
