# Generated by Django 4.1.3 on 2022-12-03 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='file_path',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logo',
            name='id',
            field=models.GenericIPAddressField(unpack_ipv4=True),
        ),
    ]
