# Generated by Django 4.1.3 on 2022-12-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0002_remove_finishmodel_id_finishmodel_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniq',
            name='ty',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
