# Generated by Django 4.1.3 on 2022-12-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0002_taos_delete_aut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taos',
            name='greet',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
