# Generated by Django 4.1.3 on 2022-12-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0002_rename_name_comment_author_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_accessed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
