# Generated by Django 4.1.3 on 2022-12-15 16:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0002_author_remove_blogtemplate_last_accessed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtemplate',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='element_one.comment'),
        ),
        migrations.AlterField(
            model_name='blogtemplate',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, max_length=130, unique=True),
        ),
    ]
