# Generated by Django 4.1.3 on 2022-12-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0003_alter_author_last_accessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
