# Generated by Django 4.1.3 on 2022-12-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0003_alter_taos_greet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taos',
            name='greet',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
