# Generated by Django 4.1.3 on 2022-12-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0003_uniq_ty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniq',
            name='ty',
        ),
    ]
