# Generated by Django 4.1.3 on 2022-12-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0004_remove_uniq_ty'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniq',
            name='ty',
            field=models.TextField(default=1, help_text='This my text'),
            preserve_default=False,
        ),
    ]
