# Generated by Django 4.1.3 on 2022-12-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0004_publisher_author_created_by_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='headshot',
            field=models.ImageField(upload_to=''),
        ),
    ]
