# Generated by Django 4.1.3 on 2022-12-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0005_alter_taos_greet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mass',
            name='ibjbk',
        ),
        migrations.AlterField(
            model_name='mass',
            name='zail',
            field=models.CharField(default=1, max_length=46),
            preserve_default=False,
        ),
    ]
