# Generated by Django 4.1.3 on 2022-12-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0005_alter_author_headshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
