# Generated by Django 4.1.3 on 2022-12-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0005_uniq_ty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greet',
            name='fees',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='greet',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
