# Generated by Django 3.2.16 on 2022-12-31 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0006_auto_20230101_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='blogtemplate',
            name='updated_by',
        ),
    ]
