# Generated by Django 3.2.16 on 2023-01-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0009_yutug_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yutug',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='yutug',
            name='updated_by',
        ),
    ]
