# Generated by Django 3.2.16 on 2023-01-01 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_one', '0011_yutug_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yutug',
            name='updated_by',
        ),
    ]
